name: healthcheck
on: [workflow_dispatch]
jobs:
  check_if_containers_up:
    runs-on: self-hosted
    steps:
    - name: check_number_of_containers
      run: echo '::set-output name=NUMBER_CONTAINERS::docker ps | wc -l'
      id: num_containers
    - name: let_job_fail_if_not_all_containers_are_up
      if:  ${{steps.num_containers.outputs.NUMBER_CONTAINERS < 6 }}
      uses:  actions/github-script@v3
      with:
        script: |
             core.setFailed("There are less than 5 containers up")
